### ISSUE TITLE
Typo in prerequisites in the README: Bio::DB::HTC vs Bio::DB::HTS

### ISSUE THREAD

**Issue by rpornmon** [rhysf/HaplotypeTools#1]
I couldn't find the `Bio::DB::HTC` in CPAN at first, but `Bio::DB::HTS` gave a clue that there might gave been a typo. It should be a quick fix? The typo is in the `prerequisites` section on top of the README file.

**Comment by rhysf** [comment]
Yes, absolutely - that should have been HTS, thanks for spotting and reporting that. I have updated the README.
