### ISSUE TITLE
non-targeted scaffolds were processed during split bam?

### ISSUE THREAD

**Issue by athlql** [rhysf/HaplotypeTools#2]
Hi, I am trying to use HaplotypeTools to phase the vcf, my main question is if there is a possibility to limit bam splitting only to targeted scaffold/regions.

My vcf was a small subset of a gvcf with 11 samples (generated using bcftools) and targeted only mRNA of a few genes. The bam files had also been subset using samtools view for reads fall under the targeted regions (using a bed file). 

During step 1, the program shows that only the targeted scaffolds in vcf were processed.

During step 2, the program shows processing of non-targeted scaffolds, which results 0 kb files in the temp folder and is taking long time.

Is it possible to run phasing on local regions?

Thank you very much.

**Comment by rhysf** [comment]
Dear @athlql 

Apologies, but there isn't currently a way implemented in HT. 

I would suggest if you are only interested in a target region, then you subset your bam/sam using other tools, and ensure that you reference fasta and VCF's also reflect that selection.

**Comment by athlql** [comment]
> Dear @athlql
> 
> Apologies, but there isn't currently a way implemented in HT.
> 
> I would suggest if you are only interested in a target region, then you subset your bam/sam using other tools, and ensure that you reference fasta and VCF's also reflect that selection.

Thanks! I will try it. 
Thanks again for the quick response.
